apiVersion: v1
kind: Service
metadata:
  name: randoli-api
spec:
  selector:
    app: event-api
  ports:
    - name: http
      port: 8080
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
spec:
  selector:
    app: postgres
  ports:
    - name: dbport
      port: 5432
      nodePort: 30010
  type: NodePort