apiVersion: v1
kind: Service
metadata:
  name: randoli-api
spec:
  selector:
    app: event-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
spec:
  selector:
    app: postgres
  ports:
    - name: dbport
      port: 5432
  type: LoadBalancer